# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mozilla-Mechanize-GUITester
version:      0.13
version_from: lib/Mozilla/Mechanize/GUITester.pm
installdirs:  site
requires:
    Class::Accessor:               
    Mozilla::ConsoleService:       0.04
    Mozilla::DOM:                  0.21
    Mozilla::DOM::ComputedStyle:   0.03
    Mozilla::Mechanize:            
    Mozilla::ObserverService:      0.03
    Mozilla::PromptService:        0.04
    Mozilla::SourceViewer:         0.06
    X11::GUITest:                  

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
