# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mozilla-Mechanize-GUITester
version:      0.11
version_from: lib/Mozilla/Mechanize/GUITester.pm
installdirs:  site
requires:
    Class::Accessor:               
    Mozilla::ConsoleService:       0.02
    Mozilla::DOM:                  
    Mozilla::DOM::ComputedStyle:   
    Mozilla::Mechanize:            
    Mozilla::ObserverService:      0.02
    Mozilla::PromptService:        0.02
    Mozilla::SourceViewer:         0.04
    X11::GUITest:                  

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
