# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mozilla-Mechanize-GUITester
version:      0.01
version_from: lib/Mozilla/Mechanize/GUITester.pm
installdirs:  site
requires:
    Class::Accessor:               
    Mozilla::DOM:                  
    Mozilla::Mechanize:            
    Mozilla::ObserverService:      
    Mozilla::PromptService:        
    X11::GUITest:                  

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
